ALTER TABLE `delivery`
  ADD COLUMN IF NOT EXISTS `to_business_at` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `arrived_business_at` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `incident_at` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `incident_reason` VARCHAR(255) NULL;
