ALTER TABLE users
ADD COLUMN avatar_url VARCHAR(255) NULL,
ADD COLUMN delivery_zone VARCHAR(120) NULL,
ADD COLUMN vehicle_type VARCHAR(40) NULL,
ADD COLUMN vehicle_plate VARCHAR(40) NULL,
ADD COLUMN delivery_notes TEXT NULL,
ADD COLUMN is_available TINYINT(1) NOT NULL DEFAULT 1;
