CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  cart_id INT NULL,
  business_id INT NOT NULL,
  address_id INT NOT NULL,
  payment_method_id INT NOT NULL,
  payment_method VARCHAR(50) NULL,
  comprobante_pago_url MEDIUMTEXT NULL,
  order_status_id INT NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  terminal_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  delivery_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  service_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  tip_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(10,2) NOT NULL,
  customer_notes VARCHAR(255) NULL,
  placed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmed_at DATETIME NULL,
  delivered_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX fk_orders_user (user_id),
  INDEX fk_orders_cart (cart_id),
  INDEX fk_orders_business (business_id),
  INDEX fk_orders_address (address_id),
  INDEX fk_orders_payment_method (payment_method_id),
  INDEX fk_orders_order_status (order_status_id)
);

CREATE TABLE IF NOT EXISTS order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  product_name_snapshot VARCHAR(120) NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  subtotal DECIMAL(10,2) NOT NULL,
  notes VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX fk_order_items_order (order_id),
  INDEX fk_order_items_product (product_id)
);
