CREATE TABLE IF NOT EXISTS addresses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  label VARCHAR(50) NULL,
  recipient_name VARCHAR(120) NULL,
  phone VARCHAR(20) NULL,
  street VARCHAR(120) NOT NULL,
  external_number VARCHAR(20) NULL,
  internal_number VARCHAR(20) NULL,
  neighborhood VARCHAR(120) NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  postal_code VARCHAR(10) NOT NULL DEFAULT '49500',
  reference_notes VARCHAR(255) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  status_id INT NOT NULL DEFAULT 1,
  created_at DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_addresses_user_id (user_id),
  INDEX idx_addresses_status_id (status_id),
  INDEX idx_addresses_is_default (is_default)
);
